# __     ___ _                  _
# \ \   / (_) |_ __ _ _ __ ___ (_)_ __    _
#  \ \ / /| | __/ _` | '_ ` _ \| | '_ \ _| |_
#   \ V / | | || (_| | | | | | | | | | |_   _|
#    \_/  |_|\__\__,_|_| |_| |_|_|_| |_| |_|

# Support: https://soystargaze.com/discord
# Source: https://github.com/soystargaze/Vitamin
# Version: 1.3.0

# Plugin settings
# Language of the plugin
language: "en_us"

# Overwrite default translation files with plugin updates if true.
# Recommended: leave true to keep defaults up-to-date.
# For custom translations, duplicate and rename default files before editing.
translations:
  force-update: true # Recommended to keep translations up-to-date. Default: true

update-check: true # Check for updates on admin join

# Database settings
database:
  type: sqlite

  # For MySQL, MariaDB and PostgreSQL:
  mysql:
    host: localhost
    port: 3306
    database: vitamin
    username: root
    password: ""

  mariadb:
    host: localhost
    port: 3306
    database: vitamin
    username: root
    password: ""

  postgresql:
    host: localhost
    port: 5432
    database: vitamin
    username: postgres
    password: ""

# Async thread pool size
settings:
  async_thread_pool_size: 4

# GUI Configuration for Restore Command
gui:
  restore:
    title: "&6Restore: %player% &7(%count% containers)"
    size: 54
    date-format: "dd/MM/yyyy HH:mm"
    item:
      display-name: "&e%container_name% &7#%short_id%"
      restored-yes: "&aYes"
      restored-no: "&cNo"
      lore:
        - "&7▸ ID: &f%short_id%..."
        - "&7▸ Picked up: &f%pickup_date%"
        - "&7▸ Location: &f%world% (%x%, %y%, %z%)"
        - "&7▸ Restored: %restored_status%"
        - ""
        - "&7Contents preview:"
        - "%contents%"
        - ""
        - "&e▶ Click to give a copy to your inventory"
      contents:
        empty: "  &8• Empty"
        item-format: "  &8• &f%amount%x &7%item_name%"
        more-format: "  &8• ... and %remaining% more items"
        max-preview: 5
    restored-item:
      display-name: "&6Restored %container_name%"
      date-format: "dd/MM/yyyy HH:mm"
      lore:
        - "&7▸ Original owner: &f%owner%"
        - "&7▸ Backup ID: &f%short_id%..."
        - "&7▸ Picked up: &f%pickup_date%"
        - "&7▸ Original location: &f%world% (%x%, %y%, %z%)"
        - ""
        - "&e▶ This is a restored copy from backup"

# Enable or disable modules
module:
  armor_trim: false # Armor trim gives special effects depending on the material (Active with Shift or Passive)
  auto_tool: false # Automatically switch to the correct tool when breaking blocks
  bone_meal_expansion: false # Bone meal can be used to grow special crops
  campfire_tweaks: false # Campfires give regeneration and saturation when sitting on them
  carry_on: false # Shift + Right Click to pick up entities and containers
  crop_protection: false # Prevents crops from being trampled
  custom_recipes: false # Add custom recipes to the game
  death_chest: false # Create a chest with your items when you die
  death_map: false # Create a map with your death location
  elevator: false # Craft an elevator block to teleport up and down
  elytra_armor: false # Elytra gives armor like a chest plate
  enchants_back: false # Enchants are returned when disenchanting with a grindstone and has empty books
  fire_aspect_tools: false # Drop's smelting when the tool has Fire Aspect I (40%) and Fire Aspect II (100%)
  invisible_item_frames: false # Right-click an item frame with an empty hand to make it invisible/visible
  leaf_decay: false # Leaves decay when the log is removed
  oxygen_bottle: false # Using an empty bottle in the water gives you some oxygen
  pet_protection: false # Prevents pets from taking damage from the owner
  player_xp_to_books: false # Shift + Right Click with an empty book to store all your XP
  repair: false # Repair items with nuggets, ingots, diamonds and netherite
  seed_replanter: false # Right-Click a fully grown crop to harvest and replant it
  replayable_vault: false # Make Vaults and Ominous Vaults replayable
  silk_spawners: false # Mine spawners with a silk touch pickaxe to get the spawner
  sponge_with_lava: false # Sponges can absorb lava
  totem_from_inventory: false # The totem of undying works from the inventory too
  void_totem: false # The totem of undying works in the void
  tp_to_bed_with_compass: false # Right-click with a compass to teleport to your respawn point
  unlock_all_recipes: false # Unlocks all recipes when you join the server
  tree_vein_miner: false # Just works when the tool is enchanted with Efficiency V
  vein_miner: false # Just works when the tool is enchanted with Efficiency V
  villager_follow_emeralds: false # Villagers follow you when you hold an emerald
  wall_jump: false # Shift to wall jump. You can climb up or slide down walls
  weather_effects: false # In the daytime, mobs have more babies and with the rain, crops grow faster.

# Bone Meal Expansion settings
bone_meal_expansion:
  crops:
    sugar_cane: true
    cactus: true
    bamboo: true
    nether_wart: true
    pumpkin_stem: true  # Just works with the pumpkin stem
    melon_stem: true    # Just works with the melon stem

# Campfire Tweaks settings
campfire_tweaks:
  regen_radius: 5                 # Radius of the regeneration effect
  regen_level: 1                  # Regeneration level (1 = Regeneration I, 2 = Regeneration II)
  regen_duration_ticks: 60        # Duration of the regeneration effect in ticks (20 ticks = 1 second)
  check_interval_ticks: 80        # Check interval for regeneration effect in ticks
  saturation_interval_ticks: 160  # Check interval for saturation effect in ticks

# Carry On settings
carry_on:
  max_weight: 100                   # Weight is based on the max health of the mob
  allow_player_pickup: false        # Allow players to pick up other players (need permission: vitamin.module.carry_on.entity.player)
  allow_lootin_pickup: false        # Block Lootin chest pickup (only if Lootin plugin is on the server)
  allow_stacking: false             # Allow stacking of players carrying other players
  prevent_container_stacking: true  # Prevent stacking of containers inside other containers

# Death Chest settings
death_chest:
  vertical_search: 30     # Vertical safe search distance
  horizontal_search: 50   # Horizontal safe search distance

# Death Map settings
death_map:
  map-scale: "CLOSEST" # Options: CLOSEST, NORMAL, FAR, FARTHEST

# Elytra Armor settings
elytra_armor:
  value: 11.0 # Value of a netherite chest plate

# Wall Jump settings
wall_jump:
  slide_speed: 0.05
  slide_particle: "BLOCK"
  slide_sound: "BLOCK_SAND_STEP"
  jump_height: 0.7
  jump_distance: 0.42
  release_height: 0.5

# TP to Respawn Point with Compass settings
tp_with_compass:
  channeling_time: 3          # Time in seconds to channel the compass
  cooldown_time: 0            # Cooldown time in seconds
  require_stationary: true    # Require the player to be stationary

# Enchants Back settings
enchants_back:
  max_returned: 5     # Maximum number of enchants returned
  random_range: true  # Random range from max_returned

# Leaf Decay settings
leaf_decay:
  decay_time: 4 # Time in seconds to decay the leaves
  max_radius: 4 # Maximum radius to decay the leaves

# Repair settings
repair:
  netherite_value: 0.8  # Percentage repaired with a netherite ingot: 80%
  diamond_value: 0.4    # Percentage repaired with a diamond: 40%
  ingot_value: 0.27     # Percentage repaired with an ingot: 27%
  nugget_value: 0.03    # Percentage repaired with a nugget: 3%

# Player XP to Books settings
xpbooks:
  max_per_book: 10000 # Maximum XP stored in a book
  efficiency: 0.95    # Efficiency of XP transfer to books (0.95 = 95% efficiency)

# Oxygen Bottle settings
oxygen_bottle:
  restore_amount: 60   # Quantity of oxygen restored (20 ticks = 1 second)

# Armor Trim settings
armor_trims:
  COPPER:
    enabled: true
    haste_on_sneak:
      enabled: true
      duration: 15  # seconds, converted to ticks (x20) in code
      cooldown: 60  # seconds
  IRON:
    enabled: true
    magnet:
      enabled: true
      base_radius: 1.0  # blocks per armor piece
  REDSTONE:
    enabled: true
    speed_on_sneak:
      enabled: true
      speed_boost: 0.05  # base speed increase per piece
      duration: 5        # seconds
  EMERALD:
    enabled: true # Hero of the Village effect
  NETHERITE:
    enabled: true
    fire_resistance:
      enabled: true
      duration: 10  # seconds per piece
      cooldown: 30  # seconds
    knockback_resistance:
      enabled: true
  LAPIS:
    enabled: true
    extra_exp:
      enabled: true
      extra_per_piece: 0.10  # extra XP percentage per piece
    enchant_exp_refund:
      enabled: true
      probability_per_piece: 0.05  # chance per piece to refund XP
      refund_percentage: 0.15      # percentage of spent XP refunded
  QUARTZ:
    enabled: true
    night_vision_on_sneak:
      enabled: true
  DIAMOND:
    enabled: true
    armor_boost:
      enabled: true
      reduction_per_piece: 0.08  # damage reduction per piece
  AMETHYST:
    enabled: true
    regeneration_on_damage:
      enabled: true
      duration: 8   # seconds per piece
      cooldown: 15  # seconds
      radius: 5.0   # blocks
  GOLD:
    enabled: true   # Controls piglin neutrality behavior

# Replayable Vault settings
replayable_vault:
  cooldown: 3600000      # Cooldown in milliseconds (1 hour default)
  max_reactivations: 2   # Max additional openings beyond the first (total 3 openings, 1 initial + 2 reactivations)