# __     ___ _                  _
# \ \   / (_) |_ __ _ _ __ ___ (_)_ __    _
#  \ \ / /| | __/ _` | '_ ` _ \| | '_ \ _| |_
#   \ V / | | || (_| | | | | | | | | | |_   _|
#    \_/  |_|\__\__,_|_| |_| |_|_|_| |_| |_|

# Support: https://soystargaze.com/discord
# Source: https://github.com/soystargaze/Vitamin
# Version: 1.3.0

# Plugin settings
# Language of the plugin
language: "en_us"

# Overwrite default translation files with plugin updates if true.
# Recommended: leave true to keep defaults up-to-date.
# For custom translations, duplicate and rename default files before editing.
translations:
  force-update: true # Recommended to keep translations up-to-date. Default: true

update-check: true # Check for updates on admin join

# Database settings
database:
  type: sqlite

  # For MySQL, MariaDB and PostgreSQL:
  mysql:
    host: localhost
    port: 3306
    database: vitamin
    username: root
    password: ""

  mariadb:
    host: localhost
    port: 3306
    database: vitamin
    username: root
    password: ""

  postgresql:
    host: localhost
    port: 5432
    database: vitamin
    username: postgres
    password: ""

# Async thread pool size
settings:
  async_thread_pool_size: 4

# Enable or disable modules
module:
  armor_trim: true # Armor trim gives special effects depending on the material (Active with Shift or Passive)
  auto_tool: true # Automatically switch to the correct tool when breaking blocks
  bone_meal_expansion: true # Bone meal can be used to grow special crops
  carry_on: true # Shift + Right Click to pick up entities and containers
  crop_protection: true # Prevents crops from being trampled
  custom_recipes: true # Add custom recipes to the game
  death_chest: true # Create a chest with your items when you die
  death_map: true # Create a map with your death location
  elevator: true # Craft an elevator block to teleport up and down
  elytra_armor: true # Elytra gives armor like a chest plate
  enchants_back: true # Enchants are returned when disenchanting with a grindstone and has empty books
  fire_aspect_tools: true # Drop's smelting when the tool has Fire Aspect I (40%) and Fire Aspect II (100%)
  invisible_item_frames: true # Right-click an item frame with an empty hand to make it invisible/visible
  leaf_decay: true # Leaves decay when the log is removed
  oxygen_bottle: true # Using an empty bottle in the water gives you some oxygen
  pet_protection: true # Prevents pets from taking damage from the owner
  player_xp_to_books: true # Shift + Right Click with an empty book to store all your XP
  repair: true # Repair items with nuggets, ingots, diamonds and netherite
  seed_replanter: true # Right-Click a fully grown crop to harvest and replant it
  replayable_vault: true # Make Vaults and Ominous Vaults replayable
  silk_spawners: true # Mine spawners with a silk touch pickaxe to get the spawner
  sponge_with_lava: true # Sponges can absorb lava
  totem_from_inventory: true # The totem of undying works from the inventory too
  void_totem: true # The totem of undying works in the void
  tp_to_bed_with_compass: true # Right-click with a compass to teleport to your respawn point
  unlock_all_recipes: true # Unlocks all recipes when you join the server
  tree_vein_miner: true # Just works when the tool is enchanted with Efficiency V
  vein_miner: true # Just works when the tool is enchanted with Efficiency V
  villager_follow_emeralds: true # Villagers follow you when you hold an emerald
  wall_jump: true # Shift to wall jump. You can climb up or slide down walls
  waystone: true # Waystone teleportation system with Magnetite pillars
  weather_effects: true # In the daytime, mobs have more babies and with the rain, crops grow faster.

# Bone Meal Expansion settings
bone_meal_expansion:
  crops:
    sugar_cane: true
    cactus: true
    bamboo: true
    nether_wart: true
    pumpkin_stem: true  # Just works with the pumpkin stem
    melon_stem: true    # Just works with the melon stem

# Carry On settings
carry_on:
  max_weight: 100            # Weight is based on the max health of the mob
  allow_player_pickup: false # Allow players to pick up other players (need permission: vitamin.module.carry_on.entity.player)
  allow_lootin_pickup: false # Block Lootin chest pickup (only if Lootin plugin is on the server)
  allow_stacking: false      # Allow stacking of players carrying other players

# Death Chest settings
death_chest:
  vertical_search: 30     # Vertical safe search distance
  horizontal_search: 50   # Horizontal safe search distance

# Death Map settings
death_map:
  map-scale: "CLOSEST" # Options: CLOSEST, NORMAL, FAR, FARTHEST

# Elytra Armor settings
elytra_armor:
  value: 11.0 # Value of a netherite chest plate

# Wall Jump settings
wall_jump:
  slide_speed: 0.05
  slide_particle: "BLOCK"
  slide_sound: "BLOCK_SAND_STEP"
  jump_height: 0.7
  jump_distance: 0.42
  release_height: 0.5

# TP to Respawn Point with Compass settings
tp_with_compass:
  channeling_time: 3          # Time in seconds to channel the compass
  cooldown_time: 0            # Cooldown time in seconds
  require_stationary: true    # Require the player to be stationary

# Enchants Back settings
enchants_back:
  max_returned: 5     # Maximum number of enchants returned
  random_range: true  # Random range from max_returned

# Leaf Decay settings
leaf_decay:
  decay_time: 4 # Time in seconds to decay the leaves
  max_radius: 4 # Maximum radius to decay the leaves

# Repair settings
repair:
  netherite_value: 0.8  # Percentage repaired with a netherite ingot: 80%
  diamond_value: 0.4    # Percentage repaired with a diamond: 40%
  ingot_value: 0.27     # Percentage repaired with an ingot: 27%
  nugget_value: 0.03    # Percentage repaired with a nugget: 3%

# Oxygen Bottle settings
oxygen_bottle:
  restore_amount: 60   # Quantity of oxygen restored (20 ticks = 1 second)

# Armor Trim settings
armor_trims:
  COPPER:
    enabled: true
    haste_on_sneak:
      enabled: true
      duration: 15  # seconds, converted to ticks (x20) in code
      cooldown: 60  # seconds
  IRON:
    enabled: true
    magnet:
      enabled: true
      base_radius: 1.0  # blocks per armor piece
  REDSTONE:
    enabled: true
    speed_on_sneak:
      enabled: true
      speed_boost: 0.05  # base speed increase per piece
      duration: 5        # seconds
  EMERALD:
    enabled: true # Hero of the Village effect
  NETHERITE:
    enabled: true
    fire_resistance:
      enabled: true
      duration: 10  # seconds per piece
      cooldown: 30  # seconds
    knockback_resistance:
      enabled: true
  LAPIS:
    enabled: true
    extra_exp:
      enabled: true
      extra_per_piece: 0.10  # extra XP percentage per piece
    enchant_exp_refund:
      enabled: true
      probability_per_piece: 0.05  # chance per piece to refund XP
      refund_percentage: 0.15      # percentage of spent XP refunded
  QUARTZ:
    enabled: true
    night_vision_on_sneak:
      enabled: true
  DIAMOND:
    enabled: true
    armor_boost:
      enabled: true
      reduction_per_piece: 0.08  # damage reduction per piece
  AMETHYST:
    enabled: true
    regeneration_on_damage:
      enabled: true
      duration: 8   # seconds per piece
      cooldown: 15  # seconds
      radius: 5.0   # blocks
  GOLD:
    enabled: true  # Controls piglin neutrality behavior

# Replayable Vault settings
replayable_vault:
  cooldown: 3600000  # Cooldown in milliseconds (1 hour default)
  max_reactivations: 2  # Max additional openings beyond the first (total 3 openings)

# Waystone settings
waystone:
  only_creator_can_break: true          # Only the creator can break the waystone
  auto_create_time: 30000               # Time in milliseconds (default: 30 seconds)
  auto_create_distance_squared: 100.0   # Distance squared (default: 10 blocks squared)
  default_name: "Waystone"              # Default name for the waystone
  teleport_delay: 3                     # Time in seconds to teleport
  cancel_teleport_on_move: true         # Cancel teleport if the player moves