name: Vitamin
version: '1.3.0'
main: com.soystargaze.vitamin.Vitamin
api-version: '1.21'
load: STARTUP
authors: [Stargaze (Eros Marí)]
website: https://soystargaze.com
softdepend:
  - WorldGuard
  - Lands
commands:
  vitamin:
    description: Main command for Vitamin
    usage: /<command> [reload|module|pmodule]
    permission: vitamin.use
    aliases:
      - vita
      - vi
permissions:
  vitamin.use:
    description: Allows use of the /vitamin command
    default: op
  vitamin.reload:
    description: Allows use of the /vitamin reload command
    default: op
  vitamin.module:
    description: Allows use of the /vitamin module command
    default: op
  vitamin.pmodule:
    description: Allows use of the /vitamin pmodule command
    default: true