name: Sync README to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      # Paso 1: Clonar el repositorio privado
      - name: Checkout private repository
        uses: actions/checkout@v3

      # Paso 2: Clonar el repositorio público con autenticación
      - name: Clone public repository
        run: |
          git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/soystargaze/Vitamin-Public.git public-repo
          cd public-repo

      # Paso 3: Configurar identidad de Git
      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Paso 4: Copiar el README.md
      - name: Copy README to public repository
        run: |
          cp README.md public-repo/
          cd public-repo
          git add README.md
          git commit -m "Actualizar README" || true
          git push || echo "No hay cambios por subir"
